logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %5p [%t] %-40.40logger{39}: %m%n%ex"
  level:
    org:
      springframework:
        web: INFO

server:
  port: ${PORT:8081}
  shutdown: graceful
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

springdoc:
  api-docs:
    path: /api-docs

spring:
  lifecycle:
    timeout-per-shutdown-phase: 1m
  cache:
    jcache:
      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
    caffeine:
      spec: maximumSize=1000000,expireAfterAccess=600s
    cache-names:
      - rate-limit-bucket

sentry:
  dsn: ${SENTRY_DSN:}

debug: true

bucket4j:
  enabled: true
  filters:
    - cache-key: getRemoteAddr()
      cache-name: rate-limit-bucket
      url: ^/api.*
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted the API usage limits \" }"
      rate-limits:
        - bandwidths:
            - capacity: 5
              time: 10
              unit: seconds
