name: Schemas-service CI

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths-ignore:
      - 'README.md'
      - 'scripts'
      - 'ui'
    branches:
      - main

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

  setup-and-test-node:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - name: Run copy-resources script
        env:
          SCHEMAS_PRIVATE_AWS_ACCESS_KEY_ID: ${{ secrets.SCHEMAS_PRIVATE_AWS_ACCESS_KEY_ID }}
          SCHEMAS_PRIVATE_AWS_SECRET_ACCESS_KEY: ${{ secrets.SCHEMAS_PRIVATE_AWS_SECRET_ACCESS_KEY }}
          SCHEMAS_PRIVATE_AWS_REGION: ${{ secrets.SCHEMAS_PRIVATE_AWS_REGION }}
          SCHEMAS_PRIVATE_S3_BUCKET_NAME: ${{ secrets.SCHEMAS_PRIVATE_S3_BUCKET_NAME }}
        run: chmod +x ./copy-resources.sh && ./copy-resources.sh
      - run: npm test