name: Schemas-service CI

# Set minimal permissions following principle of least privilege
permissions:
  contents: read  # Allow reading repository contents
  actions: read   # Allow reading workflow run information

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths-ignore:
      - 'README.md'
      - 'ui'
    branches:
      - main

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

  setup-and-test-node:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - name: Run copy-resources script
        env:
          SCHEMAS_PRIVATE_AWS_ACCESS_KEY_ID: ${{ secrets.SCHEMAS_PRIVATE_AWS_ACCESS_KEY_ID }}
          SCHEMAS_PRIVATE_AWS_SECRET_ACCESS_KEY: ${{ secrets.SCHEMAS_PRIVATE_AWS_SECRET_ACCESS_KEY }}
          SCHEMAS_PRIVATE_AWS_REGION: ${{ secrets.SCHEMAS_PRIVATE_AWS_REGION }}
          SCHEMAS_PRIVATE_S3_BUCKET_NAME: ${{ secrets.SCHEMAS_PRIVATE_S3_BUCKET_NAME }}
        run: chmod +x ./copy-resources.sh && ./copy-resources.sh
      - run: npm test

  test-json2pdf:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    # Tests the standalone json2pdf command-line tool with Maven dependencies

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven
          
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Install Node.js dependencies
        run: npm ci
        
      - name: Build Java project and copy dependencies
        run: mvn clean compile package -DskipTests -Dexec.skip=true
        
      - name: Run json2pdf tests
        run: npm run test:json2pdf