name: Deploy to Schema CDN service # (updates the S3 Bucket and clears cache of CloudFront distribution)

on:
  push:
    branches:
      - main
    paths:
      - "schemas/**/schema.json"
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GITHUB_ACTION
          role-session-name: githubactions
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync Files to S3
        run: |
          # Create a temporary directory for transformed files
          mkdir -p transformed

          # Get repository name from GitHub context
          REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')
          
          # Create 404.txt file in the root of transformed directory (only for main repository)
          if [ "$REPO_NAME" = "schemas" ]; then
            echo "Not Found" > transformed/404.txt
          fi
          
          # Find all schema.json files and create transformed copies
          find schemas -name schema.json | while read file; do
            # Extract components from path (e.g., schemas/Forestry/v0.0.1/schema.json)
            domain=$(echo "$file" | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')
            version=$(echo "$file" | cut -d'/' -f3)
            
            # TODO: replace this with a proper fix
            if [ "$domain" = "forestrysource" ]; then
              domain="forestry-source"
            fi

            # Create new path with transformed structure
            new_path="transformed/${domain}-schemas/${version}/schema.json"
            
            # Create directory structure and copy file
            mkdir -p "$(dirname "$new_path")"
            cp "$file" "$new_path"
            
            # Store the domain for sync
            echo "${domain}-schemas/*" >> patterns.txt
          done
          
          # Sync transformed directory to S3
          if [ -f patterns.txt ]; then
            # Convert patterns file to proper --include arguments
            INCLUDES=$(cat patterns.txt | while read pattern; do echo "--include $pattern"; done | tr '\n' ' ')
            
            # Debug output to verify the command
            echo "Running sync with includes: $INCLUDES"
            
            aws s3 sync transformed/ s3://schema-cdn-service-bucket \
              --delete \
              --exclude "*" \
              $INCLUDES
          fi

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
